name: Generate Binaries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 'debian:10'
    
    steps:
    - uses: actions/checkout@v1
    - name: make output directory if needed
      run: mkdir bins || exit 0
    - name: update apt
      run: apt-get update
    - name: ensure build packages are installed
      run: apt-get -y install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev gcc-arm-linux-gnueabihf gcc-arm-linux-gnueabi build-essential git 
    - name: install default linux source
      run: apt-get -y install linux-source
    - name: unpack source
      run: cd wixlcm; tar xf "/usr/src/$(ls /usr/src/ | grep linux-source)"
    - name: build armel binary
      run: cd wixlcm;ls -l; make CROSS_COMPILE="arm-linux-gnueabi-" KERNEL_SOURCE="$(ls | grep linux-source)" all
   # - name: set git user name
   #   run: git config user.name "workflow@github" 
   # - name: set git user email
   #   run: git config user.email "workflow@github"
   # - name: add new files to repo if needed
   #   run: git add bins/*
   # - name: commit new files
   #   run: git commit -a -m "commit binaries built from latest source" || exit 0
 #   - name: push changes
 #     run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
