name: Generate Binaries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 'debian:testing'
    
    steps:
    - uses: actions/checkout@v1
    - name: ensure build packages are installed
      run: apt-get update; apt-get -y install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev gcc-arm-linux-gnueabihf gcc-arm-linux-gnueabi build-essential git libssl-dev
    - name: install default linux source
      run: apt-get -y install linux-source
    - name: make
      run: cd wixlcm; chmod +x *.sh; ./cross_build.sh
   #- name: set git user name
   #   run: git config user.name "workflow@github" 
    - name: set git user email
      run: git config user.email "workflow@github"
    - name: add new files to repo if needed
      run: git add bins; git add bins/*
    - name: commit new files
      run: git commit -a -m "commit binaries built from latest source" || exit 0
 #   - name: push changes
 #     run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
